# Generated by Django 6.0.2 on 2026-02-19 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('assigned_pac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='pacapp.pacs')),
            ],
        ),
        migrations.CreateModel(
            name='PastoralNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('pac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacapp.pacs')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacapp.students')),
            ],
        ),
    ]
