# Generated by Django 6.0.2 on 2026-02-19 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='assigned_pac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='pacapp.pacs'),
        ),
    ]
