# Generated by Django 6.0.2 on 2026-02-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacapp', '0002_alter_students_assigned_pac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='enrollment_date',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='PastoralNotes',
        ),
    ]
