# Generated by Django 6.0.2 on 2026-02-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacapp', '0003_alter_students_enrollment_date_delete_pastoralnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacs',
            name='pac_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
